version: "3.9"
services:
  solana-red:
    image: solanalabs/solana:v1.9.1
    environment:
      RUST_LOG: warn
    ports:
    - "${RED_WS_PORT}:8900"
    - "${RED_HTTP_PORT}:8899"
  solana-blue:
    image: solanalabs/solana:v1.9.1
    environment:
      RUST_LOG: warn
    ports:
    - "${BLUE_WS_PORT}:8900"
    - "${BLUE_HTTP_PORT}:8899"
